/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as JoinRouteImport } from './routes/join'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AppCompaniesRouteImport } from './routes/_app/companies'
import { Route as AppDealsRouteImport } from './routes/_app/deals'
import { Route as AppDedupeRouteImport } from './routes/_app/dedupe'
import { Route as AppDocumentsRouteImport } from './routes/_app/documents'
import { Route as AppImportRouteImport } from './routes/_app/import'
import { Route as AppInboxRouteImport } from './routes/_app/inbox'
import { Route as AppMandateRouteImport } from './routes/_app/mandate'
import { Route as AppNotesRouteImport } from './routes/_app/notes'
import { Route as AppPeopleRouteImport } from './routes/_app/people'
import { Route as AppPortfolioRouteImport } from './routes/_app/portfolio'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppSpacesRouteImport } from './routes/_app/spaces'
import { Route as AppTasksRouteImport } from './routes/_app/tasks'
import { Route as AppTodayRouteImport } from './routes/_app/today'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiMcpRouteImport } from './routes/api/mcp'
import { Route as AppCompaniesCompanyIdRouteImport } from './routes/_app/companies_.$companyId'
import { Route as AppDealsDealIdRouteImport } from './routes/_app/deals_.$dealId'
import { Route as AppImportBatchIdRouteImport } from './routes/_app/import_.$batchId'
import { Route as AppNotesNoteIdRouteImport } from './routes/_app/notes_.$noteId'
import { Route as AppOObjectSlugRouteImport } from './routes/_app/o.$objectSlug'
import { Route as AppPeoplePersonIdRouteImport } from './routes/_app/people_.$personId'
import { Route as AppPortfolioHoldingIdRouteImport } from './routes/_app/portfolio_.$holdingId'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppSettingsAiRouteImport } from './routes/_app/settings/ai'
import { Route as AppSettingsArrivalRouteImport } from './routes/_app/settings/arrival'
import { Route as AppSettingsCurrencyRouteImport } from './routes/_app/settings/currency'
import { Route as AppSettingsEmbeddingsRouteImport } from './routes/_app/settings/embeddings'
import { Route as AppSettingsMembersRouteImport } from './routes/_app/settings/members'
import { Route as AppSettingsObjectsRouteImport } from './routes/_app/settings/objects'
import { Route as AppSettingsTemplatesRouteImport } from './routes/_app/settings/templates'
import { Route as AppSettingsTokensRouteImport } from './routes/_app/settings/tokens'
import { Route as AppSettingsUsageRouteImport } from './routes/_app/settings/usage'
import { Route as AppSettingsWorkspaceRouteImport } from './routes/_app/settings/workspace'
import { Route as AppSpacesSpaceIdRouteImport } from './routes/_app/spaces_.$spaceId'
import { Route as AppTermsTermIdRouteImport } from './routes/_app/terms.$termId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiBlobKeyRouteImport } from './routes/api/blob/$key'
import { Route as ApiV1SplatRouteImport } from './routes/api/v1/$'
import { Route as AppOObjectSlugRecordIdRouteImport } from './routes/_app/o_.$objectSlug.$recordId'
import { Route as AppSettingsObjectsObjectSlugRouteImport } from './routes/_app/settings/objects_.$objectSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCompaniesRoute = AppCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AppRoute,
} as any)
const AppDealsRoute = AppDealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => AppRoute,
} as any)
const AppDedupeRoute = AppDedupeRouteImport.update({
  id: '/dedupe',
  path: '/dedupe',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppImportRoute = AppImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppMandateRoute = AppMandateRouteImport.update({
  id: '/mandate',
  path: '/mandate',
  getParentRoute: () => AppRoute,
} as any)
const AppNotesRoute = AppNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AppRoute,
} as any)
const AppPeopleRoute = AppPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AppRoute,
} as any)
const AppPortfolioRoute = AppPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSpacesRoute = AppSpacesRouteImport.update({
  id: '/spaces',
  path: '/spaces',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppTodayRoute = AppTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AppRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCompaniesCompanyIdRoute = AppCompaniesCompanyIdRouteImport.update({
  id: '/companies_/$companyId',
  path: '/companies/$companyId',
  getParentRoute: () => AppRoute,
} as any)
const AppDealsDealIdRoute = AppDealsDealIdRouteImport.update({
  id: '/deals_/$dealId',
  path: '/deals/$dealId',
  getParentRoute: () => AppRoute,
} as any)
const AppImportBatchIdRoute = AppImportBatchIdRouteImport.update({
  id: '/import_/$batchId',
  path: '/import/$batchId',
  getParentRoute: () => AppRoute,
} as any)
const AppNotesNoteIdRoute = AppNotesNoteIdRouteImport.update({
  id: '/notes_/$noteId',
  path: '/notes/$noteId',
  getParentRoute: () => AppRoute,
} as any)
const AppOObjectSlugRoute = AppOObjectSlugRouteImport.update({
  id: '/o/$objectSlug',
  path: '/o/$objectSlug',
  getParentRoute: () => AppRoute,
} as any)
const AppPeoplePersonIdRoute = AppPeoplePersonIdRouteImport.update({
  id: '/people_/$personId',
  path: '/people/$personId',
  getParentRoute: () => AppRoute,
} as any)
const AppPortfolioHoldingIdRoute = AppPortfolioHoldingIdRouteImport.update({
  id: '/portfolio_/$holdingId',
  path: '/portfolio/$holdingId',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsAiRoute = AppSettingsAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsArrivalRoute = AppSettingsArrivalRouteImport.update({
  id: '/arrival',
  path: '/arrival',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsCurrencyRoute = AppSettingsCurrencyRouteImport.update({
  id: '/currency',
  path: '/currency',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsEmbeddingsRoute = AppSettingsEmbeddingsRouteImport.update({
  id: '/embeddings',
  path: '/embeddings',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsMembersRoute = AppSettingsMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsObjectsRoute = AppSettingsObjectsRouteImport.update({
  id: '/objects',
  path: '/objects',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsTemplatesRoute = AppSettingsTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsTokensRoute = AppSettingsTokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsUsageRoute = AppSettingsUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsWorkspaceRoute = AppSettingsWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSpacesSpaceIdRoute = AppSpacesSpaceIdRouteImport.update({
  id: '/spaces_/$spaceId',
  path: '/spaces/$spaceId',
  getParentRoute: () => AppRoute,
} as any)
const AppTermsTermIdRoute = AppTermsTermIdRouteImport.update({
  id: '/terms/$termId',
  path: '/terms/$termId',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBlobKeyRoute = ApiBlobKeyRouteImport.update({
  id: '/api/blob/$key',
  path: '/api/blob/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SplatRoute = ApiV1SplatRouteImport.update({
  id: '/api/v1/$',
  path: '/api/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOObjectSlugRecordIdRoute = AppOObjectSlugRecordIdRouteImport.update({
  id: '/o_/$objectSlug/$recordId',
  path: '/o/$objectSlug/$recordId',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsObjectsObjectSlugRoute =
  AppSettingsObjectsObjectSlugRouteImport.update({
    id: '/objects_/$objectSlug',
    path: '/objects/$objectSlug',
    getParentRoute: () => AppSettingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/companies': typeof AppCompaniesRoute
  '/deals': typeof AppDealsRoute
  '/dedupe': typeof AppDedupeRoute
  '/documents': typeof AppDocumentsRoute
  '/import': typeof AppImportRoute
  '/inbox': typeof AppInboxRoute
  '/mandate': typeof AppMandateRoute
  '/notes': typeof AppNotesRoute
  '/people': typeof AppPeopleRoute
  '/portfolio': typeof AppPortfolioRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/spaces': typeof AppSpacesRoute
  '/tasks': typeof AppTasksRoute
  '/today': typeof AppTodayRoute
  '/api/health': typeof ApiHealthRoute
  '/api/mcp': typeof ApiMcpRoute
  '/companies/$companyId': typeof AppCompaniesCompanyIdRoute
  '/deals/$dealId': typeof AppDealsDealIdRoute
  '/import/$batchId': typeof AppImportBatchIdRoute
  '/notes/$noteId': typeof AppNotesNoteIdRoute
  '/o/$objectSlug': typeof AppOObjectSlugRoute
  '/people/$personId': typeof AppPeoplePersonIdRoute
  '/portfolio/$holdingId': typeof AppPortfolioHoldingIdRoute
  '/settings/ai': typeof AppSettingsAiRoute
  '/settings/arrival': typeof AppSettingsArrivalRoute
  '/settings/currency': typeof AppSettingsCurrencyRoute
  '/settings/embeddings': typeof AppSettingsEmbeddingsRoute
  '/settings/members': typeof AppSettingsMembersRoute
  '/settings/objects': typeof AppSettingsObjectsRoute
  '/settings/templates': typeof AppSettingsTemplatesRoute
  '/settings/tokens': typeof AppSettingsTokensRoute
  '/settings/usage': typeof AppSettingsUsageRoute
  '/settings/workspace': typeof AppSettingsWorkspaceRoute
  '/spaces/$spaceId': typeof AppSpacesSpaceIdRoute
  '/terms/$termId': typeof AppTermsTermIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/blob/$key': typeof ApiBlobKeyRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/o/$objectSlug/$recordId': typeof AppOObjectSlugRecordIdRoute
  '/settings/objects/$objectSlug': typeof AppSettingsObjectsObjectSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/companies': typeof AppCompaniesRoute
  '/deals': typeof AppDealsRoute
  '/dedupe': typeof AppDedupeRoute
  '/documents': typeof AppDocumentsRoute
  '/import': typeof AppImportRoute
  '/inbox': typeof AppInboxRoute
  '/mandate': typeof AppMandateRoute
  '/notes': typeof AppNotesRoute
  '/people': typeof AppPeopleRoute
  '/portfolio': typeof AppPortfolioRoute
  '/spaces': typeof AppSpacesRoute
  '/tasks': typeof AppTasksRoute
  '/today': typeof AppTodayRoute
  '/api/health': typeof ApiHealthRoute
  '/api/mcp': typeof ApiMcpRoute
  '/companies/$companyId': typeof AppCompaniesCompanyIdRoute
  '/deals/$dealId': typeof AppDealsDealIdRoute
  '/import/$batchId': typeof AppImportBatchIdRoute
  '/notes/$noteId': typeof AppNotesNoteIdRoute
  '/o/$objectSlug': typeof AppOObjectSlugRoute
  '/people/$personId': typeof AppPeoplePersonIdRoute
  '/portfolio/$holdingId': typeof AppPortfolioHoldingIdRoute
  '/settings/ai': typeof AppSettingsAiRoute
  '/settings/arrival': typeof AppSettingsArrivalRoute
  '/settings/currency': typeof AppSettingsCurrencyRoute
  '/settings/embeddings': typeof AppSettingsEmbeddingsRoute
  '/settings/members': typeof AppSettingsMembersRoute
  '/settings/objects': typeof AppSettingsObjectsRoute
  '/settings/templates': typeof AppSettingsTemplatesRoute
  '/settings/tokens': typeof AppSettingsTokensRoute
  '/settings/usage': typeof AppSettingsUsageRoute
  '/settings/workspace': typeof AppSettingsWorkspaceRoute
  '/spaces/$spaceId': typeof AppSpacesSpaceIdRoute
  '/terms/$termId': typeof AppTermsTermIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/blob/$key': typeof ApiBlobKeyRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/settings': typeof AppSettingsIndexRoute
  '/o/$objectSlug/$recordId': typeof AppOObjectSlugRecordIdRoute
  '/settings/objects/$objectSlug': typeof AppSettingsObjectsObjectSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/_app/companies': typeof AppCompaniesRoute
  '/_app/deals': typeof AppDealsRoute
  '/_app/dedupe': typeof AppDedupeRoute
  '/_app/documents': typeof AppDocumentsRoute
  '/_app/import': typeof AppImportRoute
  '/_app/inbox': typeof AppInboxRoute
  '/_app/mandate': typeof AppMandateRoute
  '/_app/notes': typeof AppNotesRoute
  '/_app/people': typeof AppPeopleRoute
  '/_app/portfolio': typeof AppPortfolioRoute
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_app/spaces': typeof AppSpacesRoute
  '/_app/tasks': typeof AppTasksRoute
  '/_app/today': typeof AppTodayRoute
  '/api/health': typeof ApiHealthRoute
  '/api/mcp': typeof ApiMcpRoute
  '/_app/companies_/$companyId': typeof AppCompaniesCompanyIdRoute
  '/_app/deals_/$dealId': typeof AppDealsDealIdRoute
  '/_app/import_/$batchId': typeof AppImportBatchIdRoute
  '/_app/notes_/$noteId': typeof AppNotesNoteIdRoute
  '/_app/o/$objectSlug': typeof AppOObjectSlugRoute
  '/_app/people_/$personId': typeof AppPeoplePersonIdRoute
  '/_app/portfolio_/$holdingId': typeof AppPortfolioHoldingIdRoute
  '/_app/settings/ai': typeof AppSettingsAiRoute
  '/_app/settings/arrival': typeof AppSettingsArrivalRoute
  '/_app/settings/currency': typeof AppSettingsCurrencyRoute
  '/_app/settings/embeddings': typeof AppSettingsEmbeddingsRoute
  '/_app/settings/members': typeof AppSettingsMembersRoute
  '/_app/settings/objects': typeof AppSettingsObjectsRoute
  '/_app/settings/templates': typeof AppSettingsTemplatesRoute
  '/_app/settings/tokens': typeof AppSettingsTokensRoute
  '/_app/settings/usage': typeof AppSettingsUsageRoute
  '/_app/settings/workspace': typeof AppSettingsWorkspaceRoute
  '/_app/spaces_/$spaceId': typeof AppSpacesSpaceIdRoute
  '/_app/terms/$termId': typeof AppTermsTermIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/blob/$key': typeof ApiBlobKeyRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/o_/$objectSlug/$recordId': typeof AppOObjectSlugRecordIdRoute
  '/_app/settings/objects_/$objectSlug': typeof AppSettingsObjectsObjectSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/join'
    | '/login'
    | '/setup'
    | '/companies'
    | '/deals'
    | '/dedupe'
    | '/documents'
    | '/import'
    | '/inbox'
    | '/mandate'
    | '/notes'
    | '/people'
    | '/portfolio'
    | '/settings'
    | '/spaces'
    | '/tasks'
    | '/today'
    | '/api/health'
    | '/api/mcp'
    | '/companies/$companyId'
    | '/deals/$dealId'
    | '/import/$batchId'
    | '/notes/$noteId'
    | '/o/$objectSlug'
    | '/people/$personId'
    | '/portfolio/$holdingId'
    | '/settings/ai'
    | '/settings/arrival'
    | '/settings/currency'
    | '/settings/embeddings'
    | '/settings/members'
    | '/settings/objects'
    | '/settings/templates'
    | '/settings/tokens'
    | '/settings/usage'
    | '/settings/workspace'
    | '/spaces/$spaceId'
    | '/terms/$termId'
    | '/api/auth/$'
    | '/api/blob/$key'
    | '/api/v1/$'
    | '/settings/'
    | '/o/$objectSlug/$recordId'
    | '/settings/objects/$objectSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/join'
    | '/login'
    | '/setup'
    | '/companies'
    | '/deals'
    | '/dedupe'
    | '/documents'
    | '/import'
    | '/inbox'
    | '/mandate'
    | '/notes'
    | '/people'
    | '/portfolio'
    | '/spaces'
    | '/tasks'
    | '/today'
    | '/api/health'
    | '/api/mcp'
    | '/companies/$companyId'
    | '/deals/$dealId'
    | '/import/$batchId'
    | '/notes/$noteId'
    | '/o/$objectSlug'
    | '/people/$personId'
    | '/portfolio/$holdingId'
    | '/settings/ai'
    | '/settings/arrival'
    | '/settings/currency'
    | '/settings/embeddings'
    | '/settings/members'
    | '/settings/objects'
    | '/settings/templates'
    | '/settings/tokens'
    | '/settings/usage'
    | '/settings/workspace'
    | '/spaces/$spaceId'
    | '/terms/$termId'
    | '/api/auth/$'
    | '/api/blob/$key'
    | '/api/v1/$'
    | '/settings'
    | '/o/$objectSlug/$recordId'
    | '/settings/objects/$objectSlug'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/join'
    | '/login'
    | '/setup'
    | '/_app/companies'
    | '/_app/deals'
    | '/_app/dedupe'
    | '/_app/documents'
    | '/_app/import'
    | '/_app/inbox'
    | '/_app/mandate'
    | '/_app/notes'
    | '/_app/people'
    | '/_app/portfolio'
    | '/_app/settings'
    | '/_app/spaces'
    | '/_app/tasks'
    | '/_app/today'
    | '/api/health'
    | '/api/mcp'
    | '/_app/companies_/$companyId'
    | '/_app/deals_/$dealId'
    | '/_app/import_/$batchId'
    | '/_app/notes_/$noteId'
    | '/_app/o/$objectSlug'
    | '/_app/people_/$personId'
    | '/_app/portfolio_/$holdingId'
    | '/_app/settings/ai'
    | '/_app/settings/arrival'
    | '/_app/settings/currency'
    | '/_app/settings/embeddings'
    | '/_app/settings/members'
    | '/_app/settings/objects'
    | '/_app/settings/templates'
    | '/_app/settings/tokens'
    | '/_app/settings/usage'
    | '/_app/settings/workspace'
    | '/_app/spaces_/$spaceId'
    | '/_app/terms/$termId'
    | '/api/auth/$'
    | '/api/blob/$key'
    | '/api/v1/$'
    | '/_app/settings/'
    | '/_app/o_/$objectSlug/$recordId'
    | '/_app/settings/objects_/$objectSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  JoinRoute: typeof JoinRoute
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiMcpRoute: typeof ApiMcpRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiBlobKeyRoute: typeof ApiBlobKeyRoute
  ApiV1SplatRoute: typeof ApiV1SplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/companies': {
      id: '/_app/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof AppCompaniesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/deals': {
      id: '/_app/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof AppDealsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dedupe': {
      id: '/_app/dedupe'
      path: '/dedupe'
      fullPath: '/dedupe'
      preLoaderRoute: typeof AppDedupeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents': {
      id: '/_app/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/import': {
      id: '/_app/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AppImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inbox': {
      id: '/_app/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mandate': {
      id: '/_app/mandate'
      path: '/mandate'
      fullPath: '/mandate'
      preLoaderRoute: typeof AppMandateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notes': {
      id: '/_app/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AppNotesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/people': {
      id: '/_app/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof AppPeopleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/portfolio': {
      id: '/_app/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof AppPortfolioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/spaces': {
      id: '/_app/spaces'
      path: '/spaces'
      fullPath: '/spaces'
      preLoaderRoute: typeof AppSpacesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks': {
      id: '/_app/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/today': {
      id: '/_app/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof AppTodayRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/companies_/$companyId': {
      id: '/_app/companies_/$companyId'
      path: '/companies/$companyId'
      fullPath: '/companies/$companyId'
      preLoaderRoute: typeof AppCompaniesCompanyIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/deals_/$dealId': {
      id: '/_app/deals_/$dealId'
      path: '/deals/$dealId'
      fullPath: '/deals/$dealId'
      preLoaderRoute: typeof AppDealsDealIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/import_/$batchId': {
      id: '/_app/import_/$batchId'
      path: '/import/$batchId'
      fullPath: '/import/$batchId'
      preLoaderRoute: typeof AppImportBatchIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notes_/$noteId': {
      id: '/_app/notes_/$noteId'
      path: '/notes/$noteId'
      fullPath: '/notes/$noteId'
      preLoaderRoute: typeof AppNotesNoteIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/o/$objectSlug': {
      id: '/_app/o/$objectSlug'
      path: '/o/$objectSlug'
      fullPath: '/o/$objectSlug'
      preLoaderRoute: typeof AppOObjectSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/people_/$personId': {
      id: '/_app/people_/$personId'
      path: '/people/$personId'
      fullPath: '/people/$personId'
      preLoaderRoute: typeof AppPeoplePersonIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/portfolio_/$holdingId': {
      id: '/_app/portfolio_/$holdingId'
      path: '/portfolio/$holdingId'
      fullPath: '/portfolio/$holdingId'
      preLoaderRoute: typeof AppPortfolioHoldingIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/ai': {
      id: '/_app/settings/ai'
      path: '/ai'
      fullPath: '/settings/ai'
      preLoaderRoute: typeof AppSettingsAiRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/arrival': {
      id: '/_app/settings/arrival'
      path: '/arrival'
      fullPath: '/settings/arrival'
      preLoaderRoute: typeof AppSettingsArrivalRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/currency': {
      id: '/_app/settings/currency'
      path: '/currency'
      fullPath: '/settings/currency'
      preLoaderRoute: typeof AppSettingsCurrencyRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/embeddings': {
      id: '/_app/settings/embeddings'
      path: '/embeddings'
      fullPath: '/settings/embeddings'
      preLoaderRoute: typeof AppSettingsEmbeddingsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/members': {
      id: '/_app/settings/members'
      path: '/members'
      fullPath: '/settings/members'
      preLoaderRoute: typeof AppSettingsMembersRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/objects': {
      id: '/_app/settings/objects'
      path: '/objects'
      fullPath: '/settings/objects'
      preLoaderRoute: typeof AppSettingsObjectsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/templates': {
      id: '/_app/settings/templates'
      path: '/templates'
      fullPath: '/settings/templates'
      preLoaderRoute: typeof AppSettingsTemplatesRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/tokens': {
      id: '/_app/settings/tokens'
      path: '/tokens'
      fullPath: '/settings/tokens'
      preLoaderRoute: typeof AppSettingsTokensRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/usage': {
      id: '/_app/settings/usage'
      path: '/usage'
      fullPath: '/settings/usage'
      preLoaderRoute: typeof AppSettingsUsageRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/workspace': {
      id: '/_app/settings/workspace'
      path: '/workspace'
      fullPath: '/settings/workspace'
      preLoaderRoute: typeof AppSettingsWorkspaceRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/spaces_/$spaceId': {
      id: '/_app/spaces_/$spaceId'
      path: '/spaces/$spaceId'
      fullPath: '/spaces/$spaceId'
      preLoaderRoute: typeof AppSpacesSpaceIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/terms/$termId': {
      id: '/_app/terms/$termId'
      path: '/terms/$termId'
      fullPath: '/terms/$termId'
      preLoaderRoute: typeof AppTermsTermIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blob/$key': {
      id: '/api/blob/$key'
      path: '/api/blob/$key'
      fullPath: '/api/blob/$key'
      preLoaderRoute: typeof ApiBlobKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/$': {
      id: '/api/v1/$'
      path: '/api/v1/$'
      fullPath: '/api/v1/$'
      preLoaderRoute: typeof ApiV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/o_/$objectSlug/$recordId': {
      id: '/_app/o_/$objectSlug/$recordId'
      path: '/o/$objectSlug/$recordId'
      fullPath: '/o/$objectSlug/$recordId'
      preLoaderRoute: typeof AppOObjectSlugRecordIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/objects_/$objectSlug': {
      id: '/_app/settings/objects_/$objectSlug'
      path: '/objects/$objectSlug'
      fullPath: '/settings/objects/$objectSlug'
      preLoaderRoute: typeof AppSettingsObjectsObjectSlugRouteImport
      parentRoute: typeof AppSettingsRoute
    }
  }
}

interface AppSettingsRouteChildren {
  AppSettingsAiRoute: typeof AppSettingsAiRoute
  AppSettingsArrivalRoute: typeof AppSettingsArrivalRoute
  AppSettingsCurrencyRoute: typeof AppSettingsCurrencyRoute
  AppSettingsEmbeddingsRoute: typeof AppSettingsEmbeddingsRoute
  AppSettingsMembersRoute: typeof AppSettingsMembersRoute
  AppSettingsObjectsRoute: typeof AppSettingsObjectsRoute
  AppSettingsTemplatesRoute: typeof AppSettingsTemplatesRoute
  AppSettingsTokensRoute: typeof AppSettingsTokensRoute
  AppSettingsUsageRoute: typeof AppSettingsUsageRoute
  AppSettingsWorkspaceRoute: typeof AppSettingsWorkspaceRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppSettingsObjectsObjectSlugRoute: typeof AppSettingsObjectsObjectSlugRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsAiRoute: AppSettingsAiRoute,
  AppSettingsArrivalRoute: AppSettingsArrivalRoute,
  AppSettingsCurrencyRoute: AppSettingsCurrencyRoute,
  AppSettingsEmbeddingsRoute: AppSettingsEmbeddingsRoute,
  AppSettingsMembersRoute: AppSettingsMembersRoute,
  AppSettingsObjectsRoute: AppSettingsObjectsRoute,
  AppSettingsTemplatesRoute: AppSettingsTemplatesRoute,
  AppSettingsTokensRoute: AppSettingsTokensRoute,
  AppSettingsUsageRoute: AppSettingsUsageRoute,
  AppSettingsWorkspaceRoute: AppSettingsWorkspaceRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppSettingsObjectsObjectSlugRoute: AppSettingsObjectsObjectSlugRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppRouteChildren {
  AppCompaniesRoute: typeof AppCompaniesRoute
  AppDealsRoute: typeof AppDealsRoute
  AppDedupeRoute: typeof AppDedupeRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppImportRoute: typeof AppImportRoute
  AppInboxRoute: typeof AppInboxRoute
  AppMandateRoute: typeof AppMandateRoute
  AppNotesRoute: typeof AppNotesRoute
  AppPeopleRoute: typeof AppPeopleRoute
  AppPortfolioRoute: typeof AppPortfolioRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppSpacesRoute: typeof AppSpacesRoute
  AppTasksRoute: typeof AppTasksRoute
  AppTodayRoute: typeof AppTodayRoute
  AppCompaniesCompanyIdRoute: typeof AppCompaniesCompanyIdRoute
  AppDealsDealIdRoute: typeof AppDealsDealIdRoute
  AppImportBatchIdRoute: typeof AppImportBatchIdRoute
  AppNotesNoteIdRoute: typeof AppNotesNoteIdRoute
  AppOObjectSlugRoute: typeof AppOObjectSlugRoute
  AppPeoplePersonIdRoute: typeof AppPeoplePersonIdRoute
  AppPortfolioHoldingIdRoute: typeof AppPortfolioHoldingIdRoute
  AppSpacesSpaceIdRoute: typeof AppSpacesSpaceIdRoute
  AppTermsTermIdRoute: typeof AppTermsTermIdRoute
  AppOObjectSlugRecordIdRoute: typeof AppOObjectSlugRecordIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCompaniesRoute: AppCompaniesRoute,
  AppDealsRoute: AppDealsRoute,
  AppDedupeRoute: AppDedupeRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppImportRoute: AppImportRoute,
  AppInboxRoute: AppInboxRoute,
  AppMandateRoute: AppMandateRoute,
  AppNotesRoute: AppNotesRoute,
  AppPeopleRoute: AppPeopleRoute,
  AppPortfolioRoute: AppPortfolioRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppSpacesRoute: AppSpacesRoute,
  AppTasksRoute: AppTasksRoute,
  AppTodayRoute: AppTodayRoute,
  AppCompaniesCompanyIdRoute: AppCompaniesCompanyIdRoute,
  AppDealsDealIdRoute: AppDealsDealIdRoute,
  AppImportBatchIdRoute: AppImportBatchIdRoute,
  AppNotesNoteIdRoute: AppNotesNoteIdRoute,
  AppOObjectSlugRoute: AppOObjectSlugRoute,
  AppPeoplePersonIdRoute: AppPeoplePersonIdRoute,
  AppPortfolioHoldingIdRoute: AppPortfolioHoldingIdRoute,
  AppSpacesSpaceIdRoute: AppSpacesSpaceIdRoute,
  AppTermsTermIdRoute: AppTermsTermIdRoute,
  AppOObjectSlugRecordIdRoute: AppOObjectSlugRecordIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  JoinRoute: JoinRoute,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiMcpRoute: ApiMcpRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiBlobKeyRoute: ApiBlobKeyRoute,
  ApiV1SplatRoute: ApiV1SplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
