/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AppCompaniesRouteImport } from './routes/_app/companies'
import { Route as AppDealsRouteImport } from './routes/_app/deals'
import { Route as AppDedupeRouteImport } from './routes/_app/dedupe'
import { Route as AppNotesRouteImport } from './routes/_app/notes'
import { Route as AppPeopleRouteImport } from './routes/_app/people'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppSpacesRouteImport } from './routes/_app/spaces'
import { Route as AppThesesRouteImport } from './routes/_app/theses'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AppCompaniesCompanyIdRouteImport } from './routes/_app/companies_.$companyId'
import { Route as AppDealsDealIdRouteImport } from './routes/_app/deals_.$dealId'
import { Route as AppNotesNoteIdRouteImport } from './routes/_app/notes_.$noteId'
import { Route as AppPeoplePersonIdRouteImport } from './routes/_app/people_.$personId'
import { Route as AppSpacesSpaceIdRouteImport } from './routes/_app/spaces_.$spaceId'
import { Route as AppThesesThesisIdRouteImport } from './routes/_app/theses_.$thesisId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiBlobKeyRouteImport } from './routes/api/blob/$key'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCompaniesRoute = AppCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AppRoute,
} as any)
const AppDealsRoute = AppDealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => AppRoute,
} as any)
const AppDedupeRoute = AppDedupeRouteImport.update({
  id: '/dedupe',
  path: '/dedupe',
  getParentRoute: () => AppRoute,
} as any)
const AppNotesRoute = AppNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AppRoute,
} as any)
const AppPeopleRoute = AppPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSpacesRoute = AppSpacesRouteImport.update({
  id: '/spaces',
  path: '/spaces',
  getParentRoute: () => AppRoute,
} as any)
const AppThesesRoute = AppThesesRouteImport.update({
  id: '/theses',
  path: '/theses',
  getParentRoute: () => AppRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCompaniesCompanyIdRoute = AppCompaniesCompanyIdRouteImport.update({
  id: '/companies_/$companyId',
  path: '/companies/$companyId',
  getParentRoute: () => AppRoute,
} as any)
const AppDealsDealIdRoute = AppDealsDealIdRouteImport.update({
  id: '/deals_/$dealId',
  path: '/deals/$dealId',
  getParentRoute: () => AppRoute,
} as any)
const AppNotesNoteIdRoute = AppNotesNoteIdRouteImport.update({
  id: '/notes_/$noteId',
  path: '/notes/$noteId',
  getParentRoute: () => AppRoute,
} as any)
const AppPeoplePersonIdRoute = AppPeoplePersonIdRouteImport.update({
  id: '/people_/$personId',
  path: '/people/$personId',
  getParentRoute: () => AppRoute,
} as any)
const AppSpacesSpaceIdRoute = AppSpacesSpaceIdRouteImport.update({
  id: '/spaces_/$spaceId',
  path: '/spaces/$spaceId',
  getParentRoute: () => AppRoute,
} as any)
const AppThesesThesisIdRoute = AppThesesThesisIdRouteImport.update({
  id: '/theses_/$thesisId',
  path: '/theses/$thesisId',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBlobKeyRoute = ApiBlobKeyRouteImport.update({
  id: '/api/blob/$key',
  path: '/api/blob/$key',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/companies': typeof AppCompaniesRoute
  '/deals': typeof AppDealsRoute
  '/dedupe': typeof AppDedupeRoute
  '/notes': typeof AppNotesRoute
  '/people': typeof AppPeopleRoute
  '/settings': typeof AppSettingsRoute
  '/spaces': typeof AppSpacesRoute
  '/theses': typeof AppThesesRoute
  '/api/health': typeof ApiHealthRoute
  '/companies/$companyId': typeof AppCompaniesCompanyIdRoute
  '/deals/$dealId': typeof AppDealsDealIdRoute
  '/notes/$noteId': typeof AppNotesNoteIdRoute
  '/people/$personId': typeof AppPeoplePersonIdRoute
  '/spaces/$spaceId': typeof AppSpacesSpaceIdRoute
  '/theses/$thesisId': typeof AppThesesThesisIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/blob/$key': typeof ApiBlobKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/companies': typeof AppCompaniesRoute
  '/deals': typeof AppDealsRoute
  '/dedupe': typeof AppDedupeRoute
  '/notes': typeof AppNotesRoute
  '/people': typeof AppPeopleRoute
  '/settings': typeof AppSettingsRoute
  '/spaces': typeof AppSpacesRoute
  '/theses': typeof AppThesesRoute
  '/api/health': typeof ApiHealthRoute
  '/companies/$companyId': typeof AppCompaniesCompanyIdRoute
  '/deals/$dealId': typeof AppDealsDealIdRoute
  '/notes/$noteId': typeof AppNotesNoteIdRoute
  '/people/$personId': typeof AppPeoplePersonIdRoute
  '/spaces/$spaceId': typeof AppSpacesSpaceIdRoute
  '/theses/$thesisId': typeof AppThesesThesisIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/blob/$key': typeof ApiBlobKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/_app/companies': typeof AppCompaniesRoute
  '/_app/deals': typeof AppDealsRoute
  '/_app/dedupe': typeof AppDedupeRoute
  '/_app/notes': typeof AppNotesRoute
  '/_app/people': typeof AppPeopleRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/spaces': typeof AppSpacesRoute
  '/_app/theses': typeof AppThesesRoute
  '/api/health': typeof ApiHealthRoute
  '/_app/companies_/$companyId': typeof AppCompaniesCompanyIdRoute
  '/_app/deals_/$dealId': typeof AppDealsDealIdRoute
  '/_app/notes_/$noteId': typeof AppNotesNoteIdRoute
  '/_app/people_/$personId': typeof AppPeoplePersonIdRoute
  '/_app/spaces_/$spaceId': typeof AppSpacesSpaceIdRoute
  '/_app/theses_/$thesisId': typeof AppThesesThesisIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/blob/$key': typeof ApiBlobKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/setup'
    | '/companies'
    | '/deals'
    | '/dedupe'
    | '/notes'
    | '/people'
    | '/settings'
    | '/spaces'
    | '/theses'
    | '/api/health'
    | '/companies/$companyId'
    | '/deals/$dealId'
    | '/notes/$noteId'
    | '/people/$personId'
    | '/spaces/$spaceId'
    | '/theses/$thesisId'
    | '/api/auth/$'
    | '/api/blob/$key'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/setup'
    | '/companies'
    | '/deals'
    | '/dedupe'
    | '/notes'
    | '/people'
    | '/settings'
    | '/spaces'
    | '/theses'
    | '/api/health'
    | '/companies/$companyId'
    | '/deals/$dealId'
    | '/notes/$noteId'
    | '/people/$personId'
    | '/spaces/$spaceId'
    | '/theses/$thesisId'
    | '/api/auth/$'
    | '/api/blob/$key'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/setup'
    | '/_app/companies'
    | '/_app/deals'
    | '/_app/dedupe'
    | '/_app/notes'
    | '/_app/people'
    | '/_app/settings'
    | '/_app/spaces'
    | '/_app/theses'
    | '/api/health'
    | '/_app/companies_/$companyId'
    | '/_app/deals_/$dealId'
    | '/_app/notes_/$noteId'
    | '/_app/people_/$personId'
    | '/_app/spaces_/$spaceId'
    | '/_app/theses_/$thesisId'
    | '/api/auth/$'
    | '/api/blob/$key'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiBlobKeyRoute: typeof ApiBlobKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/companies': {
      id: '/_app/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof AppCompaniesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/deals': {
      id: '/_app/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof AppDealsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dedupe': {
      id: '/_app/dedupe'
      path: '/dedupe'
      fullPath: '/dedupe'
      preLoaderRoute: typeof AppDedupeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notes': {
      id: '/_app/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AppNotesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/people': {
      id: '/_app/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof AppPeopleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/spaces': {
      id: '/_app/spaces'
      path: '/spaces'
      fullPath: '/spaces'
      preLoaderRoute: typeof AppSpacesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/theses': {
      id: '/_app/theses'
      path: '/theses'
      fullPath: '/theses'
      preLoaderRoute: typeof AppThesesRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/companies_/$companyId': {
      id: '/_app/companies_/$companyId'
      path: '/companies/$companyId'
      fullPath: '/companies/$companyId'
      preLoaderRoute: typeof AppCompaniesCompanyIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/deals_/$dealId': {
      id: '/_app/deals_/$dealId'
      path: '/deals/$dealId'
      fullPath: '/deals/$dealId'
      preLoaderRoute: typeof AppDealsDealIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notes_/$noteId': {
      id: '/_app/notes_/$noteId'
      path: '/notes/$noteId'
      fullPath: '/notes/$noteId'
      preLoaderRoute: typeof AppNotesNoteIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/people_/$personId': {
      id: '/_app/people_/$personId'
      path: '/people/$personId'
      fullPath: '/people/$personId'
      preLoaderRoute: typeof AppPeoplePersonIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/spaces_/$spaceId': {
      id: '/_app/spaces_/$spaceId'
      path: '/spaces/$spaceId'
      fullPath: '/spaces/$spaceId'
      preLoaderRoute: typeof AppSpacesSpaceIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/theses_/$thesisId': {
      id: '/_app/theses_/$thesisId'
      path: '/theses/$thesisId'
      fullPath: '/theses/$thesisId'
      preLoaderRoute: typeof AppThesesThesisIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blob/$key': {
      id: '/api/blob/$key'
      path: '/api/blob/$key'
      fullPath: '/api/blob/$key'
      preLoaderRoute: typeof ApiBlobKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppCompaniesRoute: typeof AppCompaniesRoute
  AppDealsRoute: typeof AppDealsRoute
  AppDedupeRoute: typeof AppDedupeRoute
  AppNotesRoute: typeof AppNotesRoute
  AppPeopleRoute: typeof AppPeopleRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSpacesRoute: typeof AppSpacesRoute
  AppThesesRoute: typeof AppThesesRoute
  AppCompaniesCompanyIdRoute: typeof AppCompaniesCompanyIdRoute
  AppDealsDealIdRoute: typeof AppDealsDealIdRoute
  AppNotesNoteIdRoute: typeof AppNotesNoteIdRoute
  AppPeoplePersonIdRoute: typeof AppPeoplePersonIdRoute
  AppSpacesSpaceIdRoute: typeof AppSpacesSpaceIdRoute
  AppThesesThesisIdRoute: typeof AppThesesThesisIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCompaniesRoute: AppCompaniesRoute,
  AppDealsRoute: AppDealsRoute,
  AppDedupeRoute: AppDedupeRoute,
  AppNotesRoute: AppNotesRoute,
  AppPeopleRoute: AppPeopleRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSpacesRoute: AppSpacesRoute,
  AppThesesRoute: AppThesesRoute,
  AppCompaniesCompanyIdRoute: AppCompaniesCompanyIdRoute,
  AppDealsDealIdRoute: AppDealsDealIdRoute,
  AppNotesNoteIdRoute: AppNotesNoteIdRoute,
  AppPeoplePersonIdRoute: AppPeoplePersonIdRoute,
  AppSpacesSpaceIdRoute: AppSpacesSpaceIdRoute,
  AppThesesThesisIdRoute: AppThesesThesisIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiBlobKeyRoute: ApiBlobKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
