/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AppCompaniesRouteImport } from './routes/_app/companies'
import { Route as AppNotesRouteImport } from './routes/_app/notes'
import { Route as AppPeopleRouteImport } from './routes/_app/people'
import { Route as AppPipelineRouteImport } from './routes/_app/pipeline'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppSpacesRouteImport } from './routes/_app/spaces'
import { Route as AppThesesRouteImport } from './routes/_app/theses'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AppNotesNoteIdRouteImport } from './routes/_app/notes_.$noteId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiBlobKeyRouteImport } from './routes/api/blob/$key'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCompaniesRoute = AppCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AppRoute,
} as any)
const AppNotesRoute = AppNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AppRoute,
} as any)
const AppPeopleRoute = AppPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AppRoute,
} as any)
const AppPipelineRoute = AppPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSpacesRoute = AppSpacesRouteImport.update({
  id: '/spaces',
  path: '/spaces',
  getParentRoute: () => AppRoute,
} as any)
const AppThesesRoute = AppThesesRouteImport.update({
  id: '/theses',
  path: '/theses',
  getParentRoute: () => AppRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AppNotesNoteIdRoute = AppNotesNoteIdRouteImport.update({
  id: '/notes_/$noteId',
  path: '/notes/$noteId',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBlobKeyRoute = ApiBlobKeyRouteImport.update({
  id: '/api/blob/$key',
  path: '/api/blob/$key',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/companies': typeof AppCompaniesRoute
  '/notes': typeof AppNotesRoute
  '/people': typeof AppPeopleRoute
  '/pipeline': typeof AppPipelineRoute
  '/settings': typeof AppSettingsRoute
  '/spaces': typeof AppSpacesRoute
  '/theses': typeof AppThesesRoute
  '/api/health': typeof ApiHealthRoute
  '/notes/$noteId': typeof AppNotesNoteIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/blob/$key': typeof ApiBlobKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/companies': typeof AppCompaniesRoute
  '/notes': typeof AppNotesRoute
  '/people': typeof AppPeopleRoute
  '/pipeline': typeof AppPipelineRoute
  '/settings': typeof AppSettingsRoute
  '/spaces': typeof AppSpacesRoute
  '/theses': typeof AppThesesRoute
  '/api/health': typeof ApiHealthRoute
  '/notes/$noteId': typeof AppNotesNoteIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/blob/$key': typeof ApiBlobKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/_app/companies': typeof AppCompaniesRoute
  '/_app/notes': typeof AppNotesRoute
  '/_app/people': typeof AppPeopleRoute
  '/_app/pipeline': typeof AppPipelineRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/spaces': typeof AppSpacesRoute
  '/_app/theses': typeof AppThesesRoute
  '/api/health': typeof ApiHealthRoute
  '/_app/notes_/$noteId': typeof AppNotesNoteIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/blob/$key': typeof ApiBlobKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/setup'
    | '/companies'
    | '/notes'
    | '/people'
    | '/pipeline'
    | '/settings'
    | '/spaces'
    | '/theses'
    | '/api/health'
    | '/notes/$noteId'
    | '/api/auth/$'
    | '/api/blob/$key'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/setup'
    | '/companies'
    | '/notes'
    | '/people'
    | '/pipeline'
    | '/settings'
    | '/spaces'
    | '/theses'
    | '/api/health'
    | '/notes/$noteId'
    | '/api/auth/$'
    | '/api/blob/$key'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/setup'
    | '/_app/companies'
    | '/_app/notes'
    | '/_app/people'
    | '/_app/pipeline'
    | '/_app/settings'
    | '/_app/spaces'
    | '/_app/theses'
    | '/api/health'
    | '/_app/notes_/$noteId'
    | '/api/auth/$'
    | '/api/blob/$key'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiBlobKeyRoute: typeof ApiBlobKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/companies': {
      id: '/_app/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof AppCompaniesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notes': {
      id: '/_app/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AppNotesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/people': {
      id: '/_app/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof AppPeopleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pipeline': {
      id: '/_app/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AppPipelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/spaces': {
      id: '/_app/spaces'
      path: '/spaces'
      fullPath: '/spaces'
      preLoaderRoute: typeof AppSpacesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/theses': {
      id: '/_app/theses'
      path: '/theses'
      fullPath: '/theses'
      preLoaderRoute: typeof AppThesesRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/notes_/$noteId': {
      id: '/_app/notes_/$noteId'
      path: '/notes/$noteId'
      fullPath: '/notes/$noteId'
      preLoaderRoute: typeof AppNotesNoteIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blob/$key': {
      id: '/api/blob/$key'
      path: '/api/blob/$key'
      fullPath: '/api/blob/$key'
      preLoaderRoute: typeof ApiBlobKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppCompaniesRoute: typeof AppCompaniesRoute
  AppNotesRoute: typeof AppNotesRoute
  AppPeopleRoute: typeof AppPeopleRoute
  AppPipelineRoute: typeof AppPipelineRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSpacesRoute: typeof AppSpacesRoute
  AppThesesRoute: typeof AppThesesRoute
  AppNotesNoteIdRoute: typeof AppNotesNoteIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCompaniesRoute: AppCompaniesRoute,
  AppNotesRoute: AppNotesRoute,
  AppPeopleRoute: AppPeopleRoute,
  AppPipelineRoute: AppPipelineRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSpacesRoute: AppSpacesRoute,
  AppThesesRoute: AppThesesRoute,
  AppNotesNoteIdRoute: AppNotesNoteIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiBlobKeyRoute: ApiBlobKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
